WMS ID #6942: Corrected the image and copy tags in Task 7
oracle-livelabs/pts pull request #29
Opened 2022-08-05 15:38 UTC by rrumale

2022-08-05 18:28 UTC, arabellayao requested changes
Hi! Please make sure the image’ name is descriptive. Thanks!

2022-08-05 18:46 UTC, rrumale commented
Add image description as suggested by Arabella

2022-08-06 01:11 UTC, arabellayao submitted a review, later dismissed
Hi! Please rename the image's filename so that it is descriptive. Thank you!

2022-08-08 04:07 UTC, madhusudhanrao-ppm approved these changes

2022-08-08 04:07 UTC, merged